pkgname: mocks
packages:
  github.com/charmingruby/new/internal/billing/usecase:
    config:
      all: true
      dir: test/billing/mocks
      filename: "{{.InterfaceName}}_mock.go"
  github.com/charmingruby/new/internal/billing/repository:
    config:
      all: true
      dir: test/billing/mocks
      filename: "{{.InterfaceName}}_mock.go"
  github.com/charmingruby/new/internal/billing/client:
    config:
      all: true
      dir: test/billing/mocks
      filename: "{{.InterfaceName}}_mock.go"
  github.com/charmingruby/new/internal/shared:
    config:
      all: true
      dir: test/shared/mocks
      filename: "{{.InterfaceName}}_mock.go"
