// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TransactionManager is an autogenerated mock type for the TransactionManager type
type TransactionManager[T interface{}] struct {
	mock.Mock
}

// Transact provides a mock function with given fields: _a0
func (_m *TransactionManager[T]) Transact(_a0 func(T) error) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Transact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(T) error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionManager creates a new instance of TransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManager[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionManager[T] {
	mock := &TransactionManager[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
