// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/charmingruby/new/internal/billing/model"
	service "github.com/charmingruby/new/internal/billing/service"
	mock "github.com/stretchr/testify/mock"
)

// CatalogService is an autogenerated mock type for the CatalogService type
type CatalogService struct {
	mock.Mock
}

// CreateOffering provides a mock function with given fields: ctx, input
func (_m *CatalogService) CreateOffering(ctx context.Context, input model.OfferingInput) (service.CreateOfferingOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateOffering")
	}

	var r0 service.CreateOfferingOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OfferingInput) (service.CreateOfferingOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OfferingInput) service.CreateOfferingOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(service.CreateOfferingOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OfferingInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCatalogService creates a new instance of CatalogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogService {
	mock := &CatalogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
