// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/new/internal/billing/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateOfferingUsecase creates a new instance of MockCreateOfferingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateOfferingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateOfferingUsecase {
	mock := &MockCreateOfferingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateOfferingUsecase is an autogenerated mock type for the CreateOfferingUsecase type
type MockCreateOfferingUsecase struct {
	mock.Mock
}

type MockCreateOfferingUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateOfferingUsecase) EXPECT() *MockCreateOfferingUsecase_Expecter {
	return &MockCreateOfferingUsecase_Expecter{mock: &_m.Mock}
}

// CreateOffering provides a mock function for the type MockCreateOfferingUsecase
func (_mock *MockCreateOfferingUsecase) CreateOffering(ctx context.Context, input usecase.CreateOfferingInput) (usecase.CreateOfferingOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateOffering")
	}

	var r0 usecase.CreateOfferingOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreateOfferingInput) (usecase.CreateOfferingOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreateOfferingInput) usecase.CreateOfferingOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.CreateOfferingOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.CreateOfferingInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateOfferingUsecase_CreateOffering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOffering'
type MockCreateOfferingUsecase_CreateOffering_Call struct {
	*mock.Call
}

// CreateOffering is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateOfferingInput
func (_e *MockCreateOfferingUsecase_Expecter) CreateOffering(ctx any, input any) *MockCreateOfferingUsecase_CreateOffering_Call {
	return &MockCreateOfferingUsecase_CreateOffering_Call{Call: _e.mock.On("CreateOffering", ctx, input)}
}

func (_c *MockCreateOfferingUsecase_CreateOffering_Call) Run(run func(ctx context.Context, input usecase.CreateOfferingInput)) *MockCreateOfferingUsecase_CreateOffering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.CreateOfferingInput
		if args[1] != nil {
			arg1 = args[1].(usecase.CreateOfferingInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateOfferingUsecase_CreateOffering_Call) Return(createOfferingOutput usecase.CreateOfferingOutput, err error) *MockCreateOfferingUsecase_CreateOffering_Call {
	_c.Call.Return(createOfferingOutput, err)
	return _c
}

func (_c *MockCreateOfferingUsecase_CreateOffering_Call) RunAndReturn(run func(ctx context.Context, input usecase.CreateOfferingInput) (usecase.CreateOfferingOutput, error)) *MockCreateOfferingUsecase_CreateOffering_Call {
	_c.Call.Return(run)
	return _c
}
