// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/charmingruby/new/internal/billing/usecase"
	mock "github.com/stretchr/testify/mock"
)

// CreatePaymentUsecase is an autogenerated mock type for the CreatePaymentUsecase type
type CreatePaymentUsecase struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: ctx, input
func (_m *CreatePaymentUsecase) CreatePayment(ctx context.Context, input usecase.CreatePaymentInput) (usecase.CreatePaymentOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 usecase.CreatePaymentOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreatePaymentInput) (usecase.CreatePaymentOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreatePaymentInput) usecase.CreatePaymentOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.CreatePaymentOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreatePaymentInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreatePaymentUsecase creates a new instance of CreatePaymentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreatePaymentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreatePaymentUsecase {
	mock := &CreatePaymentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
