// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/new/internal/billing/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreatePaymentUsecase creates a new instance of MockCreatePaymentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatePaymentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatePaymentUsecase {
	mock := &MockCreatePaymentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreatePaymentUsecase is an autogenerated mock type for the CreatePaymentUsecase type
type MockCreatePaymentUsecase struct {
	mock.Mock
}

type MockCreatePaymentUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreatePaymentUsecase) EXPECT() *MockCreatePaymentUsecase_Expecter {
	return &MockCreatePaymentUsecase_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function for the type MockCreatePaymentUsecase
func (_mock *MockCreatePaymentUsecase) CreatePayment(ctx context.Context, input usecase.CreatePaymentInput) (usecase.CreatePaymentOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 usecase.CreatePaymentOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreatePaymentInput) (usecase.CreatePaymentOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreatePaymentInput) usecase.CreatePaymentOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.CreatePaymentOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.CreatePaymentInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreatePaymentUsecase_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockCreatePaymentUsecase_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreatePaymentInput
func (_e *MockCreatePaymentUsecase_Expecter) CreatePayment(ctx any, input any) *MockCreatePaymentUsecase_CreatePayment_Call {
	return &MockCreatePaymentUsecase_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, input)}
}

func (_c *MockCreatePaymentUsecase_CreatePayment_Call) Run(run func(ctx context.Context, input usecase.CreatePaymentInput)) *MockCreatePaymentUsecase_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.CreatePaymentInput
		if args[1] != nil {
			arg1 = args[1].(usecase.CreatePaymentInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreatePaymentUsecase_CreatePayment_Call) Return(createPaymentOutput usecase.CreatePaymentOutput, err error) *MockCreatePaymentUsecase_CreatePayment_Call {
	_c.Call.Return(createPaymentOutput, err)
	return _c
}

func (_c *MockCreatePaymentUsecase_CreatePayment_Call) RunAndReturn(run func(ctx context.Context, input usecase.CreatePaymentInput) (usecase.CreatePaymentOutput, error)) *MockCreatePaymentUsecase_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}
