// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/new/internal/billing/model"
	"github.com/charmingruby/new/internal/billing/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetPaymentUsecase creates a new instance of MockGetPaymentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetPaymentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetPaymentUsecase {
	mock := &MockGetPaymentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetPaymentUsecase is an autogenerated mock type for the GetPaymentUsecase type
type MockGetPaymentUsecase struct {
	mock.Mock
}

type MockGetPaymentUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetPaymentUsecase) EXPECT() *MockGetPaymentUsecase_Expecter {
	return &MockGetPaymentUsecase_Expecter{mock: &_m.Mock}
}

// GetPayment provides a mock function for the type MockGetPaymentUsecase
func (_mock *MockGetPaymentUsecase) GetPayment(ctx context.Context, input usecase.GetPaymentInput) (*model.Payment, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 *model.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.GetPaymentInput) (*model.Payment, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.GetPaymentInput) *model.Payment); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.GetPaymentInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetPaymentUsecase_GetPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayment'
type MockGetPaymentUsecase_GetPayment_Call struct {
	*mock.Call
}

// GetPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.GetPaymentInput
func (_e *MockGetPaymentUsecase_Expecter) GetPayment(ctx any, input any) *MockGetPaymentUsecase_GetPayment_Call {
	return &MockGetPaymentUsecase_GetPayment_Call{Call: _e.mock.On("GetPayment", ctx, input)}
}

func (_c *MockGetPaymentUsecase_GetPayment_Call) Run(run func(ctx context.Context, input usecase.GetPaymentInput)) *MockGetPaymentUsecase_GetPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.GetPaymentInput
		if args[1] != nil {
			arg1 = args[1].(usecase.GetPaymentInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetPaymentUsecase_GetPayment_Call) Return(payment *model.Payment, err error) *MockGetPaymentUsecase_GetPayment_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockGetPaymentUsecase_GetPayment_Call) RunAndReturn(run func(ctx context.Context, input usecase.GetPaymentInput) (*model.Payment, error)) *MockGetPaymentUsecase_GetPayment_Call {
	_c.Call.Return(run)
	return _c
}
