// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/charmingruby/new/internal/billing/model"
	usecase "github.com/charmingruby/new/internal/billing/usecase"
	mock "github.com/stretchr/testify/mock"
)

// GetPaymentUsecase is an autogenerated mock type for the GetPaymentUsecase type
type GetPaymentUsecase struct {
	mock.Mock
}

// GetPayment provides a mock function with given fields: ctx, input
func (_m *GetPaymentUsecase) GetPayment(ctx context.Context, input usecase.GetPaymentInput) (*model.Payment, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 *model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetPaymentInput) (*model.Payment, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.GetPaymentInput) *model.Payment); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.GetPaymentInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetPaymentUsecase creates a new instance of GetPaymentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetPaymentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetPaymentUsecase {
	mock := &GetPaymentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
