// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/charmingruby/new/internal/billing/usecase"
	mock "github.com/stretchr/testify/mock"
)

// ListPaymentsUsecase is an autogenerated mock type for the ListPaymentsUsecase type
type ListPaymentsUsecase struct {
	mock.Mock
}

// ListPayments provides a mock function with given fields: ctx, input
func (_m *ListPaymentsUsecase) ListPayments(ctx context.Context, input usecase.ListPaymentsInput) (usecase.ListPaymentsOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListPayments")
	}

	var r0 usecase.ListPaymentsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.ListPaymentsInput) (usecase.ListPaymentsOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.ListPaymentsInput) usecase.ListPaymentsOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.ListPaymentsOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.ListPaymentsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewListPaymentsUsecase creates a new instance of ListPaymentsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListPaymentsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListPaymentsUsecase {
	mock := &ListPaymentsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
