// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/new/internal/billing/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockListPaymentsUsecase creates a new instance of MockListPaymentsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListPaymentsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListPaymentsUsecase {
	mock := &MockListPaymentsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListPaymentsUsecase is an autogenerated mock type for the ListPaymentsUsecase type
type MockListPaymentsUsecase struct {
	mock.Mock
}

type MockListPaymentsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListPaymentsUsecase) EXPECT() *MockListPaymentsUsecase_Expecter {
	return &MockListPaymentsUsecase_Expecter{mock: &_m.Mock}
}

// ListPayments provides a mock function for the type MockListPaymentsUsecase
func (_mock *MockListPaymentsUsecase) ListPayments(ctx context.Context, input usecase.ListPaymentsInput) (usecase.ListPaymentsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListPayments")
	}

	var r0 usecase.ListPaymentsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.ListPaymentsInput) (usecase.ListPaymentsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.ListPaymentsInput) usecase.ListPaymentsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.ListPaymentsOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.ListPaymentsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListPaymentsUsecase_ListPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPayments'
type MockListPaymentsUsecase_ListPayments_Call struct {
	*mock.Call
}

// ListPayments is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.ListPaymentsInput
func (_e *MockListPaymentsUsecase_Expecter) ListPayments(ctx any, input any) *MockListPaymentsUsecase_ListPayments_Call {
	return &MockListPaymentsUsecase_ListPayments_Call{Call: _e.mock.On("ListPayments", ctx, input)}
}

func (_c *MockListPaymentsUsecase_ListPayments_Call) Run(run func(ctx context.Context, input usecase.ListPaymentsInput)) *MockListPaymentsUsecase_ListPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.ListPaymentsInput
		if args[1] != nil {
			arg1 = args[1].(usecase.ListPaymentsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListPaymentsUsecase_ListPayments_Call) Return(listPaymentsOutput usecase.ListPaymentsOutput, err error) *MockListPaymentsUsecase_ListPayments_Call {
	_c.Call.Return(listPaymentsOutput, err)
	return _c
}

func (_c *MockListPaymentsUsecase_ListPayments_Call) RunAndReturn(run func(ctx context.Context, input usecase.ListPaymentsInput) (usecase.ListPaymentsOutput, error)) *MockListPaymentsUsecase_ListPayments_Call {
	_c.Call.Return(run)
	return _c
}
