// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/charmingruby/new/internal/billing/model"
	mock "github.com/stretchr/testify/mock"
)

// OfferingRepository is an autogenerated mock type for the OfferingRepository type
type OfferingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, offering
func (_m *OfferingRepository) Create(ctx context.Context, offering *model.Offering) error {
	ret := _m.Called(ctx, offering)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Offering) error); ok {
		r0 = rf(ctx, offering)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *OfferingRepository) FindByID(ctx context.Context, id string) (*model.Offering, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Offering
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Offering, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Offering); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Offering)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *OfferingRepository) FindByName(ctx context.Context, name string) (*model.Offering, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *model.Offering
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Offering, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Offering); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Offering)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOfferingRepository creates a new instance of OfferingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOfferingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OfferingRepository {
	mock := &OfferingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
