// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/new/internal/billing/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOfferingRepository creates a new instance of MockOfferingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOfferingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOfferingRepository {
	mock := &MockOfferingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOfferingRepository is an autogenerated mock type for the OfferingRepository type
type MockOfferingRepository struct {
	mock.Mock
}

type MockOfferingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOfferingRepository) EXPECT() *MockOfferingRepository_Expecter {
	return &MockOfferingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOfferingRepository
func (_mock *MockOfferingRepository) Create(ctx context.Context, offering *model.Offering) error {
	ret := _mock.Called(ctx, offering)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Offering) error); ok {
		r0 = returnFunc(ctx, offering)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOfferingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOfferingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - offering *model.Offering
func (_e *MockOfferingRepository_Expecter) Create(ctx any, offering any) *MockOfferingRepository_Create_Call {
	return &MockOfferingRepository_Create_Call{Call: _e.mock.On("Create", ctx, offering)}
}

func (_c *MockOfferingRepository_Create_Call) Run(run func(ctx context.Context, offering *model.Offering)) *MockOfferingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Offering
		if args[1] != nil {
			arg1 = args[1].(*model.Offering)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOfferingRepository_Create_Call) Return(err error) *MockOfferingRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOfferingRepository_Create_Call) RunAndReturn(run func(ctx context.Context, offering *model.Offering) error) *MockOfferingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockOfferingRepository
func (_mock *MockOfferingRepository) FindByID(ctx context.Context, id string) (*model.Offering, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Offering
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Offering, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Offering); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Offering)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOfferingRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOfferingRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOfferingRepository_Expecter) FindByID(ctx any, id any) *MockOfferingRepository_FindByID_Call {
	return &MockOfferingRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockOfferingRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockOfferingRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOfferingRepository_FindByID_Call) Return(offering *model.Offering, err error) *MockOfferingRepository_FindByID_Call {
	_c.Call.Return(offering, err)
	return _c
}

func (_c *MockOfferingRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Offering, error)) *MockOfferingRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockOfferingRepository
func (_mock *MockOfferingRepository) FindByName(ctx context.Context, name string) (*model.Offering, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *model.Offering
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Offering, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Offering); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Offering)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOfferingRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockOfferingRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockOfferingRepository_Expecter) FindByName(ctx any, name any) *MockOfferingRepository_FindByName_Call {
	return &MockOfferingRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockOfferingRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockOfferingRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOfferingRepository_FindByName_Call) Return(offering *model.Offering, err error) *MockOfferingRepository_FindByName_Call {
	_c.Call.Return(offering, err)
	return _c
}

func (_c *MockOfferingRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Offering, error)) *MockOfferingRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}
