// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/new/internal/billing/model"
	"github.com/charmingruby/new/internal/shared/core"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Create(ctx context.Context, payment *model.Payment) error {
	ret := _mock.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Payment) error); ok {
		r0 = returnFunc(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *model.Payment
func (_e *MockPaymentRepository_Expecter) Create(ctx any, payment any) *MockPaymentRepository_Create_Call {
	return &MockPaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, payment)}
}

func (_c *MockPaymentRepository_Create_Call) Run(run func(ctx context.Context, payment *model.Payment)) *MockPaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Payment
		if args[1] != nil {
			arg1 = args[1].(*model.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Create_Call) Return(err error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, payment *model.Payment) error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByExternalID provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) FindByExternalID(ctx context.Context, externalID string) (*model.Payment, error) {
	ret := _mock.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalID")
	}

	var r0 *model.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Payment, error)); ok {
		return returnFunc(ctx, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Payment); ok {
		r0 = returnFunc(ctx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_FindByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByExternalID'
type MockPaymentRepository_FindByExternalID_Call struct {
	*mock.Call
}

// FindByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *MockPaymentRepository_Expecter) FindByExternalID(ctx any, externalID any) *MockPaymentRepository_FindByExternalID_Call {
	return &MockPaymentRepository_FindByExternalID_Call{Call: _e.mock.On("FindByExternalID", ctx, externalID)}
}

func (_c *MockPaymentRepository_FindByExternalID_Call) Run(run func(ctx context.Context, externalID string)) *MockPaymentRepository_FindByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_FindByExternalID_Call) Return(payment *model.Payment, err error) *MockPaymentRepository_FindByExternalID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockPaymentRepository_FindByExternalID_Call) RunAndReturn(run func(ctx context.Context, externalID string) (*model.Payment, error)) *MockPaymentRepository_FindByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) FindByID(ctx context.Context, id string) (*model.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPaymentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPaymentRepository_Expecter) FindByID(ctx any, id any) *MockPaymentRepository_FindByID_Call {
	return &MockPaymentRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPaymentRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockPaymentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_FindByID_Call) Return(payment *model.Payment, err error) *MockPaymentRepository_FindByID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockPaymentRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Payment, error)) *MockPaymentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) ListByUserID(ctx context.Context, userID string, params core.PaginationParams) ([]model.Payment, int, error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []model.Payment
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, core.PaginationParams) ([]model.Payment, int, error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, core.PaginationParams) []model.Payment); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, core.PaginationParams) int); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, core.PaginationParams) error); ok {
		r2 = returnFunc(ctx, userID, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPaymentRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockPaymentRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - params core.PaginationParams
func (_e *MockPaymentRepository_Expecter) ListByUserID(ctx any, userID any, params any) *MockPaymentRepository_ListByUserID_Call {
	return &MockPaymentRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, params)}
}

func (_c *MockPaymentRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string, params core.PaginationParams)) *MockPaymentRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 core.PaginationParams
		if args[2] != nil {
			arg2 = args[2].(core.PaginationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_ListByUserID_Call) Return(payments []model.Payment, n int, err error) *MockPaymentRepository_ListByUserID_Call {
	_c.Call.Return(payments, n, err)
	return _c
}

func (_c *MockPaymentRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string, params core.PaginationParams) ([]model.Payment, int, error)) *MockPaymentRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}
