// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/new/internal/billing/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentReader creates a new instance of MockPaymentReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentReader {
	mock := &MockPaymentReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentReader is an autogenerated mock type for the PaymentReader type
type MockPaymentReader struct {
	mock.Mock
}

type MockPaymentReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentReader) EXPECT() *MockPaymentReader_Expecter {
	return &MockPaymentReader_Expecter{mock: &_m.Mock}
}

// GetPayment provides a mock function for the type MockPaymentReader
func (_mock *MockPaymentReader) GetPayment(ctx context.Context, paymentID string) (*model.Payment, error) {
	ret := _mock.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 *model.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Payment, error)); ok {
		return returnFunc(ctx, paymentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Payment); ok {
		r0 = returnFunc(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentReader_GetPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayment'
type MockPaymentReader_GetPayment_Call struct {
	*mock.Call
}

// GetPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
func (_e *MockPaymentReader_Expecter) GetPayment(ctx any, paymentID any) *MockPaymentReader_GetPayment_Call {
	return &MockPaymentReader_GetPayment_Call{Call: _e.mock.On("GetPayment", ctx, paymentID)}
}

func (_c *MockPaymentReader_GetPayment_Call) Run(run func(ctx context.Context, paymentID string)) *MockPaymentReader_GetPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentReader_GetPayment_Call) Return(payment *model.Payment, err error) *MockPaymentReader_GetPayment_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockPaymentReader_GetPayment_Call) RunAndReturn(run func(ctx context.Context, paymentID string) (*model.Payment, error)) *MockPaymentReader_GetPayment_Call {
	_c.Call.Return(run)
	return _c
}
