// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/charmingruby/new/internal/billing/model"
	mock "github.com/stretchr/testify/mock"
)

// PaymentReader is an autogenerated mock type for the PaymentReader type
type PaymentReader struct {
	mock.Mock
}

// GetPayment provides a mock function with given fields: ctx, paymentID
func (_m *PaymentReader) GetPayment(ctx context.Context, paymentID string) (*model.Payment, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 *model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Payment, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Payment); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentReader creates a new instance of PaymentReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentReader {
	mock := &PaymentReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
