// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/charmingruby/new/internal/billing/model"
	service "github.com/charmingruby/new/internal/billing/service"
	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: ctx, input
func (_m *PaymentService) CreatePayment(ctx context.Context, input service.CreatePaymentInput) (service.CreatePaymentOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 service.CreatePaymentOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.CreatePaymentInput) (service.CreatePaymentOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.CreatePaymentInput) service.CreatePaymentOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(service.CreatePaymentOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.CreatePaymentInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPayment provides a mock function with given fields: ctx, input
func (_m *PaymentService) GetPayment(ctx context.Context, input service.GetPaymentInput) (*model.Payment, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 *model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.GetPaymentInput) (*model.Payment, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.GetPaymentInput) *model.Payment); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.GetPaymentInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPayments provides a mock function with given fields: ctx, input
func (_m *PaymentService) ListPayments(ctx context.Context, input service.ListPaymentsInput) (service.ListPaymentsOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListPayments")
	}

	var r0 service.ListPaymentsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.ListPaymentsInput) (service.ListPaymentsOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.ListPaymentsInput) service.ListPaymentsOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(service.ListPaymentsOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.ListPaymentsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
