// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/lab/internal/ticket/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAssignTicketUsecase creates a new instance of MockAssignTicketUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssignTicketUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssignTicketUsecase {
	mock := &MockAssignTicketUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssignTicketUsecase is an autogenerated mock type for the AssignTicketUsecase type
type MockAssignTicketUsecase struct {
	mock.Mock
}

type MockAssignTicketUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssignTicketUsecase) EXPECT() *MockAssignTicketUsecase_Expecter {
	return &MockAssignTicketUsecase_Expecter{mock: &_m.Mock}
}

// AssignTicket provides a mock function for the type MockAssignTicketUsecase
func (_mock *MockAssignTicketUsecase) AssignTicket(ctx context.Context, input usecase.AssignTicketInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AssignTicket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.AssignTicketInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAssignTicketUsecase_AssignTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignTicket'
type MockAssignTicketUsecase_AssignTicket_Call struct {
	*mock.Call
}

// AssignTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.AssignTicketInput
func (_e *MockAssignTicketUsecase_Expecter) AssignTicket(ctx any, input any) *MockAssignTicketUsecase_AssignTicket_Call {
	return &MockAssignTicketUsecase_AssignTicket_Call{Call: _e.mock.On("AssignTicket", ctx, input)}
}

func (_c *MockAssignTicketUsecase_AssignTicket_Call) Run(run func(ctx context.Context, input usecase.AssignTicketInput)) *MockAssignTicketUsecase_AssignTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.AssignTicketInput
		if args[1] != nil {
			arg1 = args[1].(usecase.AssignTicketInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAssignTicketUsecase_AssignTicket_Call) Return(err error) *MockAssignTicketUsecase_AssignTicket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAssignTicketUsecase_AssignTicket_Call) RunAndReturn(run func(ctx context.Context, input usecase.AssignTicketInput) error) *MockAssignTicketUsecase_AssignTicket_Call {
	_c.Call.Return(run)
	return _c
}
