// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/lab/internal/ticket/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateTicketUsecase creates a new instance of MockCreateTicketUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateTicketUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateTicketUsecase {
	mock := &MockCreateTicketUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateTicketUsecase is an autogenerated mock type for the CreateTicketUsecase type
type MockCreateTicketUsecase struct {
	mock.Mock
}

type MockCreateTicketUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateTicketUsecase) EXPECT() *MockCreateTicketUsecase_Expecter {
	return &MockCreateTicketUsecase_Expecter{mock: &_m.Mock}
}

// CreateTicket provides a mock function for the type MockCreateTicketUsecase
func (_mock *MockCreateTicketUsecase) CreateTicket(ctx context.Context, input usecase.CreateTicketInput) (usecase.CreateTicketOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicket")
	}

	var r0 usecase.CreateTicketOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreateTicketInput) (usecase.CreateTicketOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreateTicketInput) usecase.CreateTicketOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.CreateTicketOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.CreateTicketInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreateTicketUsecase_CreateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicket'
type MockCreateTicketUsecase_CreateTicket_Call struct {
	*mock.Call
}

// CreateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateTicketInput
func (_e *MockCreateTicketUsecase_Expecter) CreateTicket(ctx any, input any) *MockCreateTicketUsecase_CreateTicket_Call {
	return &MockCreateTicketUsecase_CreateTicket_Call{Call: _e.mock.On("CreateTicket", ctx, input)}
}

func (_c *MockCreateTicketUsecase_CreateTicket_Call) Run(run func(ctx context.Context, input usecase.CreateTicketInput)) *MockCreateTicketUsecase_CreateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.CreateTicketInput
		if args[1] != nil {
			arg1 = args[1].(usecase.CreateTicketInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateTicketUsecase_CreateTicket_Call) Return(createTicketOutput usecase.CreateTicketOutput, err error) *MockCreateTicketUsecase_CreateTicket_Call {
	_c.Call.Return(createTicketOutput, err)
	return _c
}

func (_c *MockCreateTicketUsecase_CreateTicket_Call) RunAndReturn(run func(ctx context.Context, input usecase.CreateTicketInput) (usecase.CreateTicketOutput, error)) *MockCreateTicketUsecase_CreateTicket_Call {
	_c.Call.Return(run)
	return _c
}
