// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/new/internal/ticket/model"
	"github.com/charmingruby/new/internal/ticket/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetTicketUsecase creates a new instance of MockGetTicketUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetTicketUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetTicketUsecase {
	mock := &MockGetTicketUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetTicketUsecase is an autogenerated mock type for the GetTicketUsecase type
type MockGetTicketUsecase struct {
	mock.Mock
}

type MockGetTicketUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetTicketUsecase) EXPECT() *MockGetTicketUsecase_Expecter {
	return &MockGetTicketUsecase_Expecter{mock: &_m.Mock}
}

// GetTicket provides a mock function for the type MockGetTicketUsecase
func (_mock *MockGetTicketUsecase) GetTicket(ctx context.Context, input usecase.GetTicketInput) (*model.Ticket, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetTicket")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.GetTicketInput) (*model.Ticket, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.GetTicketInput) *model.Ticket); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.GetTicketInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetTicketUsecase_GetTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicket'
type MockGetTicketUsecase_GetTicket_Call struct {
	*mock.Call
}

// GetTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.GetTicketInput
func (_e *MockGetTicketUsecase_Expecter) GetTicket(ctx any, input any) *MockGetTicketUsecase_GetTicket_Call {
	return &MockGetTicketUsecase_GetTicket_Call{Call: _e.mock.On("GetTicket", ctx, input)}
}

func (_c *MockGetTicketUsecase_GetTicket_Call) Run(run func(ctx context.Context, input usecase.GetTicketInput)) *MockGetTicketUsecase_GetTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.GetTicketInput
		if args[1] != nil {
			arg1 = args[1].(usecase.GetTicketInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetTicketUsecase_GetTicket_Call) Return(ticket *model.Ticket, err error) *MockGetTicketUsecase_GetTicket_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockGetTicketUsecase_GetTicket_Call) RunAndReturn(run func(ctx context.Context, input usecase.GetTicketInput) (*model.Ticket, error)) *MockGetTicketUsecase_GetTicket_Call {
	_c.Call.Return(run)
	return _c
}
