// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/lab/internal/ticket/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockListTicketsUsecase creates a new instance of MockListTicketsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListTicketsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListTicketsUsecase {
	mock := &MockListTicketsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListTicketsUsecase is an autogenerated mock type for the ListTicketsUsecase type
type MockListTicketsUsecase struct {
	mock.Mock
}

type MockListTicketsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListTicketsUsecase) EXPECT() *MockListTicketsUsecase_Expecter {
	return &MockListTicketsUsecase_Expecter{mock: &_m.Mock}
}

// ListTickets provides a mock function for the type MockListTicketsUsecase
func (_mock *MockListTicketsUsecase) ListTickets(ctx context.Context, input usecase.ListTicketsInput) (usecase.ListTicketsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListTickets")
	}

	var r0 usecase.ListTicketsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.ListTicketsInput) (usecase.ListTicketsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.ListTicketsInput) usecase.ListTicketsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.ListTicketsOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.ListTicketsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListTicketsUsecase_ListTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTickets'
type MockListTicketsUsecase_ListTickets_Call struct {
	*mock.Call
}

// ListTickets is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.ListTicketsInput
func (_e *MockListTicketsUsecase_Expecter) ListTickets(ctx any, input any) *MockListTicketsUsecase_ListTickets_Call {
	return &MockListTicketsUsecase_ListTickets_Call{Call: _e.mock.On("ListTickets", ctx, input)}
}

func (_c *MockListTicketsUsecase_ListTickets_Call) Run(run func(ctx context.Context, input usecase.ListTicketsInput)) *MockListTicketsUsecase_ListTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.ListTicketsInput
		if args[1] != nil {
			arg1 = args[1].(usecase.ListTicketsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListTicketsUsecase_ListTickets_Call) Return(listTicketsOutput usecase.ListTicketsOutput, err error) *MockListTicketsUsecase_ListTickets_Call {
	_c.Call.Return(listTicketsOutput, err)
	return _c
}

func (_c *MockListTicketsUsecase_ListTickets_Call) RunAndReturn(run func(ctx context.Context, input usecase.ListTicketsInput) (usecase.ListTicketsOutput, error)) *MockListTicketsUsecase_ListTickets_Call {
	_c.Call.Return(run)
	return _c
}
