// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/lab/internal/shared/core"
	"github.com/charmingruby/lab/internal/ticket/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketRepository creates a new instance of MockTicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketRepository {
	mock := &MockTicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketRepository is an autogenerated mock type for the TicketRepository type
type MockTicketRepository struct {
	mock.Mock
}

type MockTicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketRepository) EXPECT() *MockTicketRepository_Expecter {
	return &MockTicketRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) Create(ctx context.Context, ticket *model.Ticket) error {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Ticket) error); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTicketRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket *model.Ticket
func (_e *MockTicketRepository_Expecter) Create(ctx any, ticket any) *MockTicketRepository_Create_Call {
	return &MockTicketRepository_Create_Call{Call: _e.mock.On("Create", ctx, ticket)}
}

func (_c *MockTicketRepository_Create_Call) Run(run func(ctx context.Context, ticket *model.Ticket)) *MockTicketRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Ticket
		if args[1] != nil {
			arg1 = args[1].(*model.Ticket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_Create_Call) Return(err error) *MockTicketRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_Create_Call) RunAndReturn(run func(ctx context.Context, ticket *model.Ticket) error) *MockTicketRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) FindByID(ctx context.Context, id string) (*model.Ticket, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Ticket, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Ticket); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTicketRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTicketRepository_Expecter) FindByID(ctx any, id any) *MockTicketRepository_FindByID_Call {
	return &MockTicketRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTicketRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockTicketRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_FindByID_Call) Return(ticket *model.Ticket, err error) *MockTicketRepository_FindByID_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Ticket, error)) *MockTicketRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStatus provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) ListByStatus(ctx context.Context, status string, params core.PaginationParams) ([]model.Ticket, int, error) {
	ret := _mock.Called(ctx, status, params)

	if len(ret) == 0 {
		panic("no return value specified for ListByStatus")
	}

	var r0 []model.Ticket
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, core.PaginationParams) ([]model.Ticket, int, error)); ok {
		return returnFunc(ctx, status, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, core.PaginationParams) []model.Ticket); ok {
		r0 = returnFunc(ctx, status, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, core.PaginationParams) int); ok {
		r1 = returnFunc(ctx, status, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, core.PaginationParams) error); ok {
		r2 = returnFunc(ctx, status, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTicketRepository_ListByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStatus'
type MockTicketRepository_ListByStatus_Call struct {
	*mock.Call
}

// ListByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - params core.PaginationParams
func (_e *MockTicketRepository_Expecter) ListByStatus(ctx any, status any, params any) *MockTicketRepository_ListByStatus_Call {
	return &MockTicketRepository_ListByStatus_Call{Call: _e.mock.On("ListByStatus", ctx, status, params)}
}

func (_c *MockTicketRepository_ListByStatus_Call) Run(run func(ctx context.Context, status string, params core.PaginationParams)) *MockTicketRepository_ListByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 core.PaginationParams
		if args[2] != nil {
			arg2 = args[2].(core.PaginationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketRepository_ListByStatus_Call) Return(tickets []model.Ticket, n int, err error) *MockTicketRepository_ListByStatus_Call {
	_c.Call.Return(tickets, n, err)
	return _c
}

func (_c *MockTicketRepository_ListByStatus_Call) RunAndReturn(run func(ctx context.Context, status string, params core.PaginationParams) ([]model.Ticket, int, error)) *MockTicketRepository_ListByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTicketRepository
func (_mock *MockTicketRepository) Update(ctx context.Context, ticket *model.Ticket) error {
	ret := _mock.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Ticket) error); ok {
		r0 = returnFunc(ctx, ticket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTicketRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket *model.Ticket
func (_e *MockTicketRepository_Expecter) Update(ctx any, ticket any) *MockTicketRepository_Update_Call {
	return &MockTicketRepository_Update_Call{Call: _e.mock.On("Update", ctx, ticket)}
}

func (_c *MockTicketRepository_Update_Call) Run(run func(ctx context.Context, ticket *model.Ticket)) *MockTicketRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Ticket
		if args[1] != nil {
			arg1 = args[1].(*model.Ticket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepository_Update_Call) Return(err error) *MockTicketRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepository_Update_Call) RunAndReturn(run func(ctx context.Context, ticket *model.Ticket) error) *MockTicketRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
