// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/charmingruby/lab/internal/ticket/model"
	"github.com/charmingruby/lab/internal/ticket/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// AssignTicket provides a mock function for the type MockUsecase
func (_mock *MockUsecase) AssignTicket(ctx context.Context, input usecase.AssignTicketInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AssignTicket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.AssignTicketInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_AssignTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignTicket'
type MockUsecase_AssignTicket_Call struct {
	*mock.Call
}

// AssignTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.AssignTicketInput
func (_e *MockUsecase_Expecter) AssignTicket(ctx any, input any) *MockUsecase_AssignTicket_Call {
	return &MockUsecase_AssignTicket_Call{Call: _e.mock.On("AssignTicket", ctx, input)}
}

func (_c *MockUsecase_AssignTicket_Call) Run(run func(ctx context.Context, input usecase.AssignTicketInput)) *MockUsecase_AssignTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.AssignTicketInput
		if args[1] != nil {
			arg1 = args[1].(usecase.AssignTicketInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_AssignTicket_Call) Return(err error) *MockUsecase_AssignTicket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_AssignTicket_Call) RunAndReturn(run func(ctx context.Context, input usecase.AssignTicketInput) error) *MockUsecase_AssignTicket_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTicket provides a mock function for the type MockUsecase
func (_mock *MockUsecase) CreateTicket(ctx context.Context, input usecase.CreateTicketInput) (usecase.CreateTicketOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicket")
	}

	var r0 usecase.CreateTicketOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreateTicketInput) (usecase.CreateTicketOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreateTicketInput) usecase.CreateTicketOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.CreateTicketOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.CreateTicketInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_CreateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicket'
type MockUsecase_CreateTicket_Call struct {
	*mock.Call
}

// CreateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.CreateTicketInput
func (_e *MockUsecase_Expecter) CreateTicket(ctx any, input any) *MockUsecase_CreateTicket_Call {
	return &MockUsecase_CreateTicket_Call{Call: _e.mock.On("CreateTicket", ctx, input)}
}

func (_c *MockUsecase_CreateTicket_Call) Run(run func(ctx context.Context, input usecase.CreateTicketInput)) *MockUsecase_CreateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.CreateTicketInput
		if args[1] != nil {
			arg1 = args[1].(usecase.CreateTicketInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_CreateTicket_Call) Return(createTicketOutput usecase.CreateTicketOutput, err error) *MockUsecase_CreateTicket_Call {
	_c.Call.Return(createTicketOutput, err)
	return _c
}

func (_c *MockUsecase_CreateTicket_Call) RunAndReturn(run func(ctx context.Context, input usecase.CreateTicketInput) (usecase.CreateTicketOutput, error)) *MockUsecase_CreateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicket provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetTicket(ctx context.Context, input usecase.GetTicketInput) (*model.Ticket, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetTicket")
	}

	var r0 *model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.GetTicketInput) (*model.Ticket, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.GetTicketInput) *model.Ticket); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.GetTicketInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicket'
type MockUsecase_GetTicket_Call struct {
	*mock.Call
}

// GetTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.GetTicketInput
func (_e *MockUsecase_Expecter) GetTicket(ctx any, input any) *MockUsecase_GetTicket_Call {
	return &MockUsecase_GetTicket_Call{Call: _e.mock.On("GetTicket", ctx, input)}
}

func (_c *MockUsecase_GetTicket_Call) Run(run func(ctx context.Context, input usecase.GetTicketInput)) *MockUsecase_GetTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.GetTicketInput
		if args[1] != nil {
			arg1 = args[1].(usecase.GetTicketInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_GetTicket_Call) Return(ticket *model.Ticket, err error) *MockUsecase_GetTicket_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockUsecase_GetTicket_Call) RunAndReturn(run func(ctx context.Context, input usecase.GetTicketInput) (*model.Ticket, error)) *MockUsecase_GetTicket_Call {
	_c.Call.Return(run)
	return _c
}

// ListTickets provides a mock function for the type MockUsecase
func (_mock *MockUsecase) ListTickets(ctx context.Context, input usecase.ListTicketsInput) (usecase.ListTicketsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListTickets")
	}

	var r0 usecase.ListTicketsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.ListTicketsInput) (usecase.ListTicketsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.ListTicketsInput) usecase.ListTicketsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(usecase.ListTicketsOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.ListTicketsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_ListTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTickets'
type MockUsecase_ListTickets_Call struct {
	*mock.Call
}

// ListTickets is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.ListTicketsInput
func (_e *MockUsecase_Expecter) ListTickets(ctx any, input any) *MockUsecase_ListTickets_Call {
	return &MockUsecase_ListTickets_Call{Call: _e.mock.On("ListTickets", ctx, input)}
}

func (_c *MockUsecase_ListTickets_Call) Run(run func(ctx context.Context, input usecase.ListTicketsInput)) *MockUsecase_ListTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.ListTicketsInput
		if args[1] != nil {
			arg1 = args[1].(usecase.ListTicketsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_ListTickets_Call) Return(listTicketsOutput usecase.ListTicketsOutput, err error) *MockUsecase_ListTickets_Call {
	_c.Call.Return(listTicketsOutput, err)
	return _c
}

func (_c *MockUsecase_ListTickets_Call) RunAndReturn(run func(ctx context.Context, input usecase.ListTicketsInput) (usecase.ListTicketsOutput, error)) *MockUsecase_ListTickets_Call {
	_c.Call.Return(run)
	return _c
}
